# Pandas Essential Training

**Pandas** = Panel data (data over multiple time period)
- Ideal for tabular data manipulation

Main data structures
1. Series = single column
2. DataFrame = rows and columns

## Using pandas

In [2]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [4]:
pd.__version__

'2.2.2'

In [5]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [6]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers.readers:

read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: "int | Sequence[int] | None | Literal['infer']" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols: 'UsecolsArgType' = None, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters: 'Mapping[Hashable, Callable] | None' = None, true_values: 'list | None' = None, false_values: 'list | None' = None, skipinitialspace: 'bool' = False, skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool | lib.NoDefault' = <no_default>, skip_blank_lines: 'bool' = True, parse_dates: 'bool | Sequence[Hashable] | None' = None, infer_datetime_format: 'bool | lib.NoDefault' = <no_default>, keep_date_col: 'bool | lib.NoDefault' = <no_default>, date_parser: 'Callable | lib.NoDefault' = <no_default>, date_format: 'str | dict[Hashable, str] | None' = None, dayfirst: 'bool' = False, cache_dates: 'bool' = True, iterator: 'bool' = False, chunksize: 'int | None' = None, compression: 'CompressionOptions' = 'infer', thousands: 'str | None' = None, decimal: 'str' = '.', lineterminator: 'str | None' = None, quotechar: 'str' = '"', quoting: 'int' = 0, doublequote: 'bool' = True, escapechar: 'str | None' = None, comment: 'str | None' = None, encoding: 'str | None' = None, encoding_errors: 'str | None' = 'strict', dialect: 'str | csv.Dialect | None' = None, on_bad_lines: 'str' = 'error', delim_whitespace: 'bool | lib.NoDefault' = <no_default>, low_memory: 'bool' = True, memory_map: 'bool' = False, float_precision: "Literal['high', 'legacy'] | None" = None, storage_options: 'StorageOptions | None' = None, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>) -> 'DataFrame | TextFileReader'
    Read a comma-separated values (csv) file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
    sep : str, default ','
        Character or regex pattern to treat as the delimiter. If ``sep=None``, the
        C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator from only the first valid
        row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
        In addition, separators longer than 1 character and different from
        ``'\s+'`` will be interpreted as regular expressions and will also force
        the use of the Python parsing engine. Note that regex delimiters are prone
        to ignoring quoted data. Regex example: ``'\r\t'``.
    delimiter : str, optional
        Alias for ``sep``.
    header : int, Sequence of int, 'infer' or None, default 'infer'
        Row number(s) containing column labels and marking the start of the
        data (zero-indexed). Default behavior is to infer the column names: if no ``names``
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly to ``names`` then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a :class:`~pandas.MultiIndex` on the columns
        e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
        data rather than the first line of the file.
    names : Sequence of Hashable, optional
        Sequence of column labels to apply. If the file contains a header row,
        then you should explicitly pass ``header=0`` to override the column names.
        Duplicates in this list are not allowed.
    index_col : Hashable, Sequence of Hashable or False, optional
      Column(s) to use as row label(s), denoted either by column labels or column
      indices.  If a sequence of labels or indices is given, :class:`~pandas.MultiIndex`
      will be formed for the row labels.

      Note: ``index_col=False`` can be used to force pandas to *not* use the first
      column as the index, e.g., when you have a malformed file with delimiters at
      the end of each line.
    usecols : Sequence of Hashable or Callable, optional
        Subset of columns to select, denoted either by column labels or column indices.
        If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in ``names`` or
        inferred from the document header row(s). If ``names`` are given, the document
        header row(s) are not taken into account. For example, a valid list-like
        ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
        Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
        preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
        for columns in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to ``True``. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    dtype : dtype or dict of {Hashable : dtype}, optional
        Data type(s) to apply to either the whole dataset or individual columns.
        E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
        Use ``str`` or ``object`` together with suitable ``na_values`` settings
        to preserve and not interpret ``dtype``.
        If ``converters`` are specified, they will be applied INSTEAD
        of ``dtype`` conversion.

        .. versionadded:: 1.5.0

            Support for ``defaultdict`` was added. Specify a ``defaultdict`` as input where
            the default determines the ``dtype`` of the columns which are not explicitly
            listed.
    engine : {'c', 'python', 'pyarrow'}, optional
        Parser engine to use. The C and pyarrow engines are faster, while the python engine
        is currently more feature-complete. Multithreading is currently only supported by
        the pyarrow engine.

        .. versionadded:: 1.4.0

            The 'pyarrow' engine was added as an *experimental* engine, and some features
            are unsupported, or may not work correctly, with this engine.
    converters : dict of {Hashable : Callable}, optional
        Functions for converting values in specified columns. Keys can either
        be column labels or column indices.
    true_values : list, optional
        Values to consider as ``True`` in addition to case-insensitive variants of 'True'.
    false_values : list, optional
        Values to consider as ``False`` in addition to case-insensitive variants of 'False'.
    skipinitialspace : bool, default False
        Skip spaces after delimiter.
    skiprows : int, list of int or Callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (``int``)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning ``True`` if the row should be skipped and ``False`` otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
    nrows : int, optional
        Number of rows of file to read. Useful for reading pieces of large files.
    na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable}, optional
        Additional strings to recognize as ``NA``/``NaN``. If ``dict`` passed, specific
        per-column ``NA`` values.  By default the following values are interpreted as
        ``NaN``: " ", "#N/A", "#N/A N/A", "#NA", "-1.#IND", "-1.#QNAN", "-NaN", "-nan",
        "1.#IND", "1.#QNAN", "<NA>", "N/A", "NA", "NULL", "NaN", "None",
        "n/a", "nan", "null ".

    keep_default_na : bool, default True
        Whether or not to include the default ``NaN`` values when parsing the data.
        Depending on whether ``na_values`` is passed in, the behavior is as follows:

        * If ``keep_default_na`` is ``True``, and ``na_values`` are specified, ``na_values``
          is appended to the default ``NaN`` values used for parsing.
        * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
          the default ``NaN`` values are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
          the ``NaN`` values specified ``na_values`` are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
          strings will be parsed as ``NaN``.

        Note that if ``na_filter`` is passed in as ``False``, the ``keep_default_na`` and
        ``na_values`` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of ``na_values``). In
        data without any ``NA`` values, passing ``na_filter=False`` can improve the
        performance of reading a large file.
    verbose : bool, default False
        Indicate number of ``NA`` values placed in non-numeric columns.

        .. deprecated:: 2.2.0
    skip_blank_lines : bool, default True
        If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
    parse_dates : bool, list of Hashable, list of lists or dict of {Hashable : list}, default False
        The behavior is as follows:

        * ``bool``. If ``True`` -> try parsing the index. Note: Automatically set to
          ``True`` if ``date_format`` or ``date_parser`` arguments have been passed.
        * ``list`` of ``int`` or names. e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
          each as a separate date column.
        * ``list`` of ``list``. e.g.  If ``[[1, 3]]`` -> combine columns 1 and 3 and parse
          as a single date column. Values are joined with a space before parsing.
        * ``dict``, e.g. ``{'foo' : [1, 3]}`` -> parse columns 1, 3 as date and call
          result 'foo'. Values are joined with a space before parsing.

        If a column or index cannot be represented as an array of ``datetime``,
        say because of an unparsable value or a mixture of timezones, the column
        or index will be returned unaltered as an ``object`` data type. For
        non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
        :func:`~pandas.read_csv`.

        Note: A fast-path exists for iso8601-formatted dates.
    infer_datetime_format : bool, default False
        If ``True`` and ``parse_dates`` is enabled, pandas will attempt to infer the
        format of the ``datetime`` strings in the columns, and if it can be inferred,
        switch to a faster method of parsing them. In some cases this can increase
        the parsing speed by 5-10x.

        .. deprecated:: 2.0.0
            A strict version of this argument is now the default, passing it has no effect.

    keep_date_col : bool, default False
        If ``True`` and ``parse_dates`` specifies combining multiple columns then
        keep the original columns.
    date_parser : Callable, optional
        Function to use for converting a sequence of string columns to an array of
        ``datetime`` instances. The default uses ``dateutil.parser.parser`` to do the
        conversion. pandas will try to call ``date_parser`` in three different ways,
        advancing to the next if an exception occurs: 1) Pass one or more arrays
        (as defined by ``parse_dates``) as arguments; 2) concatenate (row-wise) the
        string values from the columns defined by ``parse_dates`` into a single array
        and pass that; and 3) call ``date_parser`` once for each row using one or
        more strings (corresponding to the columns defined by ``parse_dates``) as
        arguments.

        .. deprecated:: 2.0.0
           Use ``date_format`` instead, or read in as ``object`` and then apply
           :func:`~pandas.to_datetime` as-needed.
    date_format : str or dict of column -> format, optional
        Format to use for parsing dates when used in conjunction with ``parse_dates``.
        The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
        `strftime documentation
        <https://docs.python.org/3/library/datetime.html
        #strftime-and-strptime-behavior>`_ for more information on choices, though
        note that :const:`"%f"` will parse all the way up to nanoseconds.
        You can also pass:

        - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
            time string (not necessarily in exactly the same format);
        - "mixed", to infer the format for each element individually. This is risky,
            and you should probably use it along with `dayfirst`.

        .. versionadded:: 2.0.0
    dayfirst : bool, default False
        DD/MM format dates, international and European format.
    cache_dates : bool, default True
        If ``True``, use a cache of unique, converted dates to apply the ``datetime``
        conversion. May produce significant speed-up when parsing duplicate
        date strings, especially ones with timezone offsets.

    iterator : bool, default False
        Return ``TextFileReader`` object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, optional
        Number of lines to read from the file per chunk. Passing a value will cause the
        function to return a ``TextFileReader`` object for iteration.
        See the `IO Tools docs
        <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.

    compression : str or dict, default 'infer'
        For on-the-fly decompression of on-disk data. If 'infer' and 'filepath_or_buffer' is
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
        (otherwise no compression).
        If using 'zip' or 'tar', the ZIP file must contain only one data file to be read in.
        Set to ``None`` for no decompression.
        Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for Zstandard decompression using a
        custom compression dictionary:
        ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

        .. versionadded:: 1.5.0
            Added support for `.tar` files.

        .. versionchanged:: 1.4.0 Zstandard support.

    thousands : str (length 1), optional
        Character acting as the thousands separator in numerical values.
    decimal : str (length 1), default '.'
        Character to recognize as decimal point (e.g., use ',' for European data).
    lineterminator : str (length 1), optional
        Character used to denote a line break. Only valid with C parser.
    quotechar : str (length 1), optional
        Character used to denote the start and end of a quoted item. Quoted
        items can include the ``delimiter`` and it will be ignored.
    quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL, 2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
        ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that only fields containing special
        characters are quoted (e.g., characters defined in ``quotechar``, ``delimiter``,
        or ``lineterminator``.
    doublequote : bool, default True
       When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
       whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
       field as a single ``quotechar`` element.
    escapechar : str (length 1), optional
        Character used to escape other characters.
    comment : str (length 1), optional
        Character indicating that the remainder of line should not be parsed.
        If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter ``header`` but not by
        ``skiprows``. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
        treated as the header.
    encoding : str, optional, default 'utf-8'
        Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

    encoding_errors : str, optional, default 'strict'
        How encoding errors are treated. `List of possible values
        <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

        .. versionadded:: 1.3.0

    dialect : str or csv.Dialect, optional
        If provided, this parameter will override values (default or not) for the
        following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
        ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
        override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
        documentation for more details.
    on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
        Specifies what to do upon encountering a bad line (a line with too many fields).
        Allowed values are :

        - ``'error'``, raise an Exception when a bad line is encountered.
        - ``'warn'``, raise a warning when a bad line is encountered and skip that line.
        - ``'skip'``, skip bad lines without raising or warning when they are encountered.

        .. versionadded:: 1.3.0

        .. versionadded:: 1.4.0


In [7]:
pd.read_csv?

Pandas documentation: https://pandas.pydata.org/docs/reference/index.html

### Chapter 1: Reading tabular data into pandas

In [8]:
# Download the CSV data file from GitHub into the current directory.
!wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

--2026-04-05 06:17:06--  https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/jonfernandes/pandas_essential/main/olympics_1896_2004.csv [following]
--2026-04-05 06:17:06--  https://raw.githubusercontent.com/jonfernandes/pandas_essential/main/olympics_1896_2004.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2398388 (2.3M) [text/plain]
Saving to: ‘olympics_1896_2004.csv’

olympics_1896_2004. 100%[===================>]   2.29M  --.-KB/s    in 0.01s

2026-04-05 06:17:06 (210 MB/s) - ‘olympics_1896_2004.csv’ saved [2398388/2398388]

In [ ]:
# If I have my own dataset and I want to upload my own CSV file, I can run this and choose a file from my computer to upload.

#from google.colab import files
#files.upload()

In [9]:
!ls -la

total 2360
drwxr-xr-x 1 root root    4096 Apr  5 06:17 .
drwxr-xr-x 1 root root    4096 Apr  5 05:36 ..
drwxr-xr-x 4 root root    4096 Apr  2 13:31 .config
-rw-r--r-- 1 root root 2398388 Apr  5 06:17 olympics_1896_2004.csv
drwxr-xr-x 1 root root    4096 Apr  2 13:31 sample_data

In [10]:
pd.read_csv?

After reading the CSV file, notice that there columns are "unnamed" and there are several rows of NAN values. If you check the original CSV file in excel, you'll see that the first 5 rows are actually not tabular data, but the description of the dataset and a disclaimer.

In [11]:
pd.read_csv('olympics_1896_2004.csv')

,"This is a list of medallists at the Summer Olympic Games (1896-2004) with details of the year of the olympics, city, sport, discipline, athlete name, gender, event and medal",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"DISCLAIMER: No guarantees, express or implied,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
...,...,...,...,...,...,...,...,...,...,...,...
27174,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold,1
27175,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold,1
27176,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2
27177,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2
27178,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2

In [13]:
# Skip the first 5 rows since they are not actually data.
filename = "olympics_1896_2004.csv"
oo = pd.read_csv(filename, skiprows=5)
oo    # --> oo is a DataFrame

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1
...,...,...,...,...,...,...,...,...,...,...,...
27169,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold,1
27170,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold,1
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2

#### Exercise 1.4

In [18]:
from google.colab import files
files.upload()

Saving Orbis_Pictus_Award.csv to Orbis_Pictus_Award.csv

{'Orbis_Pictus_Award.csv': b'\xef\xbb\xbfYear,Title,Authors,Publisher,ISBN\r\n2025,Borderlands and the Mexican American Story,David Dorado Romo,Crown Books for Young Readers,\r\n2025,Ode to Grapefruit: How James Earl Jones Found His Voice,"Kari Lavelle, illustrated by Bryan Collier",Alfred A. Knopf,\r\n2025,Life After Whale: The Amazing Ecosystem of a Whale Fall,"Lynn Brunelle, illustrated by Jason Chin",Neal Porter Books,\r\n2025,Behold the Hummingbird!,"Suzanne Slade, illustrated by Thomas Gonzalez",Peachtree,\r\n2025,Space: The Final Pooping Frontier,"Annabeth Bondor-Stone and Connor White, illustrated by Lars Kenseth",Godwin Books,\r\n2024,The Fire of Stars: The Life and Brilliance of the Woman Who Discovered What Stars are Made Of,"Kirsten W. Larsen, illustrated by Katherine Roy",Chronicle Books,\r\n2024,Indigenous Ingenuity: A Celebration of Traditional North American Knowledge,"Deidre Havrelock & Edward Kay, illustrated by Kalila Fuller",Christy Ottaviano Books,\r\n2024,"Hidden Systems: Water, Electricity, the Internet, and the Secrets behind the Systems We Use Every Day",Dan Nott,Random House Graphic,\r\n2024,Ketanji Brown Jackson: A Justice for All,"Tami Charles, illustrated by Jemma Skidmore",Simon & Schuster Books for Young Readers,\r\n2024,Game of Freedom: Mestre Bimba and the Art of Capoeira,Duncan Tonatiuh,Abrams Books for Young Readers,\r\n2023,Choosing Brave: How Mamie Till-Mobley and Emmett Till Sparked the Civil Rights Movement,"Angela Joy, illustrated by Janelle Washington",Roaring Brook Press,\r\n2023,Fighting for Yes! The Story of Disability Rights Activist Judith Heumann,"Maryann Cocca-Leffler, illustrated by Vivien Mildenberger",Abrams Books for Young Readers,\r\n2023,Hardcourt: Stories from 75 Years of the National Basketball Association,"Fred Bowen, illustrated by James E. Ransome",Margaret K. McElderry Books,\r\n2023,"Seen and Unseen: What Dorothea Lange, Toyo Miyatake, and Ansel Adams\xe2\x80\x99s Photographs Reveal about the Japanese\nAmerican Incarceration","Elizabeth Partridge, illustrated by Lauren Tamaki",Chronicle,\r\n2023,"The Science of Light: Things That Shine, Flash, and Glow",Margaret Peot,Holiday House,\r\n2022,"Fallout: Spies, Superbombs, and The Ultimate Cold War Showdown",Steve Sheinkin,Roaring Brook Press,\r\n2022,Latinitas: Celebrating 40 Big Dreamers,Juliet Men\xc3\xa9ndez,Henry Holt and Company,\r\n2022,"Classified: The Secret Career of Mary Golda Ross, Cherokee Aerospace Engineer","Traci Sorell, illustrated by Natasha Donovan",Millbrook Press,\r\n2022,Call and Response: The Story of Black Lives Matter,Veronica Chambers,Versify,\r\n2022,Unbound: The Life & Art of Judith Scott,"Joyce Scott, with Brie Spangler and Melissa Sweet, illustrated by\nMelissa Sweet",Knopf Books for Young Readers,\r\n2021,Lifting as We Climb: Black Women\'s Battle for the Ballot Box,Evette Dionne,,\r\n2021,The Teachers March! How Selma\xe2\x80\x99s Teachers Changed History,"Sandra Neil Wallace & Rich Wallace, illustrated by Charly Palmer",,\r\n2021,All Thirteen: The Incredible Cave Rescue of the Thai Boys\xe2\x80\x99 Soccer Team,Christina Soontornvat,,\r\n2021,Honeybee: The Busy Life of Apis Mellifera,"Candace Fleming, illustrated by Eric Rohmann",,\r\n2021,If You Take Away the Otter,"Susannah Buhrman-Deever, illustrated by Matthew Trueman",,\r\n2020,Manhattan: Mapping the Story of an Island,Jennifer Thermes,Abrams,\r\n2020,Soldier for Equality: Jos\xc3\xa9 de la luz S\xc3\xa1enz and the Great War,Duncan Tonatiuh,Harry N. Abrams,\r\n2020,1919: The Year that Changed America,Martin W. Sandler,Bloomsbury,\r\n2020,The Poison Eaters: Fighting Danger and Fraud in Our Food and Drugs,Gail Jarrow,Calkins Creek,\r\n2020,Planting Stories: The Life of Librarian and Storyteller Pura Belpr\xc3\xa9,"Aneka Aldamuy Denise, illustrated by Paola Escobar",HarperCollins,\r\n2019,Champion: The Comeback Tale of the American Chestnut Tree,Sally M. Walker,"Henry Holt and\nCompany",\r\n2019,Pass Go and Collect $200: The Story of How Monopoly was Invented,"Tanya Lee Stone, illustrated by Stephen Salerno",Henry Holt and Company,\r\n2019,"The Secret Kingdom: Nek Chand, a Changing India, and a Hidden World of Art","Barb Rosenstock, illustrated by Claire A. Nivola",Candlewick Press,\r\n2019,Thirty Minutes Over Oregon: A Japanese Pilot\xe2\x80\x99s World War II Story,"Marc Tyler Nobleman, illustrated by Melissa Iwai",Clarion Books,\r\n2019,We are Grateful: Otsaliheliga,"Traci Sorrel, illustrated by Fran\xc3\xa9 Lessac",Charlesbridge Publishing,\r\n2018,Chef Roy Choi and the Street Food Remix,"Jacqueline Briggs Martin and June Jo Lee, illustrated by Man One",Readers to Eaters,\r\n2018,Dazzle Ships: World War I and the Art of Confusion,"Chris Barton, illustrated by Victo Ngai",Millbrook Press,\r\n2018,Her Right Foot,"Dave Eggers, illustrated by Shawn Harris",Chronicle Books,\r\n2018,The Quilts of Gee\xe2\x80\x99s Bend,Susan Goldman Rubin,Abrams Books for Young Readers,\r\n2018,The World is Not a Rectangle: A Portrait of Architect Zaha Hadid,Jeanette Winter,Beach Lane Books,\r\n2017,Animals by the Numbers: A Book of Animal Infographics,Steve Jenkins,Houghton Mifflin Harcourt Books for Young Readers,\r\n2017,The First Step: How One Girl Put Segregation on Trial,"Susan E. Goodman, illustrated by E. B. Lewis",Bloomsbury,\r\n2017,Giant Squid,"Candace Fleming, illustrated by Eric Rohmann",Roaring Brook Press,\r\n2017,I Dissent: Ruth Bader Ginsburg Makes Her Mark,"Debbie Levy, illustrated by Elizabeth Baddeley",Simon & Schuster Books for Young Readers,\r\n2017,"\xc2\xa1Olinguito, de la A a la Z!: Descubriendo el bosque nublado / Olinguito, from A to Z: Unveiling the Cloud Forest",Lulu Delacre,Children\xe2\x80\x99s Book Press,\r\n2016,Funny Bones: Posada and His Day of the Dead Calaveras,Duncan Tonatiuh,Abrams Books for Young Readers,\r\n2016,Growing Up Pedro,Matt Tavares,Candlewick,\r\n2016,Mesmerized: How Ben Franklin Solved a Mystery that Baffled All of France,"Mara Rockliff, illustrated by Iacopo Bruno",Candlewick,\r\n2016,Swan: The Life and Dance of Anna Pavlova,"Laurel Snyder, illustrated by Julie Morstad",Chronicle Books,\r\n2016,Terrible Typhoid Mary: A True Story of the Deadliest Cook in America, Susan Campbell Bartoletti,Houghton Mifflin Harcourt Books for Young Readers,\r\n2015,A Home for Mr. Emerson,Barbara Kerley illustrated by Edwin Fotheringham,Scholastic Press,\r\n2015,Mr. Ferris and His Wheel,Kathryn Gibbs Davis illustrated by Gilbert Ford,Houghton Mifflin Harcourt,\r\n2015,The Right Word: Roget and His Thesaurus,"Jen Bryant, illustrated by Melissa Sweet",Eerdmans Books for Young Readers,\r\n2015,Separate is Never Equal: Sylvia Mendez & Her Family\xe2\x80\x99s Fight for Desegregation,Duncan Tonatiuh,Abrams Books for Young Readers,\r\n2015,Star Stuff: Carl Sagan and the Mysteries of the Cosmos,Stephanie Roth Sisson,Roaring Brook Press,\r\n2014,Locomotive,Brian Floca,Atheneum Books for Young Readers,\r\n2014,The Boy Who Loved Math: The Improbable Life of Paul Erdos,"Deborah Heiligman, illustrated by LeUyen Pham",Roaring Brook Press,\r\n2014,Brave Girl: Clara and the Shirtwaist Makers\xe2\x80\x99 Strike of 1909,"Michelle Markel, illustrated by Melissa Sweet",Balzer + Bray,\r\n2014,Parrots Over Puerto Rico,Susan L. Roth and Cindy Trumbore,Lee & Low Books Inc.,\r\n2014,"Courage Has No Color: The True Story of the Triple Nickles, America\'s First Black Paratroopers",Tanya Lee Stone,Candlewick Press,\r\n2013,Citizen Scientists: Be a Part of Scientific Discovery from Your Own Backyard,"Loree Griffin Burns, photos by Ellen Harasimowicz",Henry Holt & Company,\r\n2013,Electric Ben: The Amazing Life and Times of Benjamin Franklin,Robert Byrd,Dial Books for Young Readers,\r\n2013,The Mighty Mars Rovers: The Incredible Adventures of Spirit and Opportunity, Elizabeth Rusch,Houghton Mifflin Books for Children,\r\n2013,"Those Rebels, John & Tom","Barbara Kerley, illustrated by Edwin Fotheringham",Scholastic,\r\n2013,We\'ve Got a Job: The 1963 Birmingham Children\xe2\x80\x99s March,Cynthia Levinson,Peachtree Publishers,\r\n2012,Amelia Lost: The Life and Disappearance of Amelia Earhart,Candace Fleming,Schwartz & Wade Books,\r\n2012,Father Abraham: Lincoln and His Sons,Harold Holzer,Calkins Creek,\r\n2012,Pablo Neruda: Poet of the People,Monica Brown illustrated by Julie Paschkis,Henry Holt and Company,\r\n2012,Terezin: Voices from the Holocaust,Ruth Thomson,Candlewick Press,\r\n2012,The Mangrove Tree: Planting Trees to Feed Families,Susan L. Roth & Cindy Trumbore,Lee & Low Books Inc.,\r\n2011,Birmingham Sunday,Larry Dane Brimner,Calkins Creek,\r\n2011,"Candy Bomber: The Story of the Berlin Airlift\'s ""Chocolate Pilot""",Michael O. Tunnell,Charlesbridge,\r\n2011,If Stones Could Speak: Unlocking the Secrets of Stonehenge,Mark Aronson,National Geographic,\r\n2011,Journey into the Deep: Discovering New Ocean Creatures,Rebecca L. Johnson,Millbrook Press,\r\n2011,Mammoths and Mastodons: Titans of the Ice Age,Cheryl Bardoe,Abrams Books for Young Readers,\r\n2010,Almost Astronauts: 13 Women Who Dared to Dream,Tanya Lee Stone,Candlewick Press,\r\n2010,Darwin: With Glimpses into His Private Journal and Letters,Alice B. McGinty,Houghton Mifflin Books for Children,\r\n2010,The Frog Scientist,Pamela S. Turner,Houghton Mifflin Books for Children,\r\n2010,How Many Baby Pandas?,Sandra Markle,Walker Books for Young Readers,\r\n2010,Noah Webster: Weaver of Words,Pegi Deitz Shea,Calkins Creek Books,\r\n2009,George Washington Carver,Tonya Bolden,Abrams Books for Young Readers,\r\n2009,The Lincolns: A Scrapbook Look at Abraham and Mary,Candace Fleming,Schwartz & Wade Books,\r\n2009,Washington at Valley Forge, Russell Freedman,Holiday House,\r\n2009,We are the Ship: The Story of Negro League Baseball,Kadir Nelson,Hyperion Books for Children,\r\n2009,When the Wolves Returned: Restoring Nature\'s Balance in Yellowstone,"Dorothy Hinshaw Patent, illustrated by Dan and Cassie Hartman",Walker Books for Young Readers,\r\n2008,Black and White Airman: Their True History,John Fleischman,Houghton Mifflin Books for Children,\r\n2008,Spiders,Nic Bishop,Scholastic,\r\n2008,Helen Keller: Her Life in Pictures,George Sullivan,Scholastic,\r\n2008,Muckrakers,Ann Bausum,National Geographic,\r\n2008,Venom,Marilyn Singer,Darby Creek Publishing,\r\n2007,Gregor Mendel: The Friar Who Grew Peas,"Cheryl Bardoe, illustrated by Jos. A. Smith",Abrams Books for Young Readers,\r\n2007,Freedom Walkers: The Story of the Montgomery Bus Boycott,Russell Freedman,Holiday House,\r\n2007,John Muir: America\xe2\x80\x99s First Environmentalist,"Kathryn Lasky, illustrated by Stan Fellows",Candlewick Press,\r\n2007,Something Out of Nothing: Marie Curie and Radium,Carla Killough McClafferty,"Farrar, Straus and Giroux",\r\n2007,"Team Moon: How 400,000 People Landed Apollo 11 on the Moon",Catherine Thimmesh,Houghton Mifflin,\r\n2006,ER Vets: Life in an Animal Emergency Room,Donna Jackson,Houghton Mifflin Books for Children,\r\n2006,"Forbidden Schoolhouse: The True and Dramatic Story of Prudence Crandall and\nHer Students",Suzanne Jurmain,Houghton Mifflin,\r\n2006,Genius: A Photobiography of Albert Einstein,Marfe Ferguson Delano,National Geographic,\r\n2006,Hitler Youth: Growing Up in Hitler\xe2\x80\x99s Shadow,Susan Campbell Bartoletti,Scholastic,\r\n2006,Mosquito Bite,Alexandra Siy and Dennis Kunkel,Charlesbridge Publishing,\r\n2005,Actual Size,Steve Jenkins,Houghton Mifflin,\r\n2005,The Race to Save the Lord God Bird,Phillip Hoose,"Farrar, Straus and Giroux",\r\n2005,Secrets of the Sphinx,James Cross Giblin illustrated by Bagram Ibatoulline,Scholastic,\r\n2005,Seurat and La Grande Jatte: Connecting the Dots,Robert Burleigh,Abrams Books for Young Readers,\r\n2005,The Voice That Challenged A Nation: Marian Anderson and the Struggle for Equal Rights,Russell Freedman,Clarion Books,\r\n2004,Empire State Building: When New York Reached for the Skies,"Elizabeth Mann, illustrated by Alan Witschonke",Mikaya Press,\r\n2004,In Defense of Liberty: The Story of America\xe2\x80\x99s Bill of Rights,Russell Freedman,Holiday House,\r\n2004,Leonardo: Beautiful Dreamer,Robert Byrd,Dutton Children\xe2\x80\x99s Books,\r\n2004,The Man Who Made Time Travel,"Kathryn Lasky, illustrated by Kevin Hawkes","Farrar, Straus and Giroux",\r\n2004,"Shutting Out the Sky: Life in the Tenements of New York, 1880-1924",Deborah Hopkinson,Orchard Books,\r\n2003,Confucius: The Golden Rule,"Russell Freedman, illustrated by Frederic Clement",Arthur A. Levine Books,\r\n2003,Emperor\'s Silent Army: Terracotta Warriors of Ancient China,Jane O\xe2\x80\x99Connor,Viking Children\xe2\x80\x99s Books,\r\n2003,Phineas Gage: A Gruesome but True Story About Brain Science,John Fleischman,Houghton Mifflin,\r\n2003,Tenement: Immigrant Life on the Lower East Side,Raymond Bial,Houghton Mifflin,\r\n2003,To Fly: The Story of the Wright Brothers,"Wendie C. Old, illustrated by Robert Andrew Parker",Clarion Books,\r\n2002,The Cod\xe2\x80\x99s Tale,"Mark Kurlansky, illustrated by S.D. Schindler",Penguin Putnam Books,\r\n2002,"The Dinosaurs of Waterhouse Hawkins: An Illuminating History of Mr. Waterhouse\nHawkins, Artist and Lecturer","Barbara Kerley, illustrated by Brian Selznick",Scholastic Press,\r\n2002,"Martin\xe2\x80\x99s Big Words: The Life of Dr. Martin Luther King, Jr.","Doreen Rappaport, illustrated by Bryan Collier",Hyperion Books for Children,\r\n2001,The Amazing Life of Benjamin Franklin,"James Giblin, illustrated by Michael\nDooling",Scholastic,\r\n2001,America\xe2\x80\x99s Champion Swimmer: Gertrude Ederle,"David A. Adler, illustrated by\nTerry Widener",Gulliver Books,\r\n2001,Michelangelo,Diane Stanley,HarperCollins Juvenile Books,\r\n2001,Osceola: Memories of a Sharecropper\xe2\x80\x99s Daughter,"Alan B. Govenar, illustrated by Shane Evans",Jump at the Sun,\r\n2001,Wild & Swampy,Jim Arnosky,HarperCollins Juvenile Books,\r\n2000,At Her Majesty\xe2\x80\x99s Request: An African Princess in Victorian England,Walter Dean Myers,Scholastic,\r\n2000,Clara Schumann: Piano Virtuoso,Susanna Reich,Clarion Books,\r\n2000,Mapping the World,Sylvia A. Johnson,Atheneum,\r\n2000,The Snake Scientist,"Sy Montgomery, illustrated by Nic Bishop",Houghton Mifflin,\r\n2000,The Top of the World: Climbing Mount Everest,Steve Jenkins,Houghton Mifflin,\r\n1999,Black Whiteness: Admiral Byrd Alone in the Antarctic,"Robert Burleigh, illustrated by Walter Lyon Krudop",Atheneum,\r\n1999,Fossil Feud: The Rivalry of the First American Dinosaur Hunters,Thom Holmes,Messner,\r\n1999,"Hottest, Coldest, Highest, Deepest",Steve Jenkins,Houghton,\r\n1999,No Pretty Pictures: A Child of War,Anita Lobel,Greenwillow,\r\n1998,A Drop of Water: A Book of Science and Wonder,Walter Wick,Scholastic,\r\n1998,A Tree is Growing,Arthur Dorros,Scholastic,\r\n1998,Charles A. Lindbergh: A Human Hero,James Cross Giblin,Clarion,\r\n1998,Kennedy Assassinated! The World Mourns: A Reporter\xe2\x80\x99s Story,Wilborn Hampton,Candlewick,\r\n1998,Digger: The Tragic Fate of the California Indians from the Missions to the Gold Rush,Jerry Stanley,Crown,\r\n1997,Full Steam Ahead: The Race to Build a Transcontinental Railroad,Rhonda Blumberg,National Geographic Society,\r\n1997,The Life and Death of Crazy Horse,Russell Freedman,Holiday House,\r\n1997,"One World, Many Religions: The Ways We Worship",Mary Pope Osborne,Alfred A. Knopf,\r\n1996,Dolphin Man: Exploring the World of Dolphins,"Lawrence Pringle, photographs by Randall S. Wells",Atheneum,\r\n1996,Rosie the Riveter: Women Working on the Home Front in World War II,Penny Colman,Crown,\r\n1995,"Christmas in the Big House, Christmas in the Quarters","Patricia C. McKissack\nand Frederick L. McKissack",Scholastic,\r\n1995,Kids at Work: Lewis Hine and the Crusade Against Child Labor,Russell Freedman,Clarion,\r\n1995,Wildlife Rescue: The Work of Dr. Kathleen Ramsay,Jennifer Owings Dewey,Boyds Mills Press,\r\n1994,Making Sense: Animal Perception and Communication,Bruce Brooks,"Farrar, Straus & Giroux, Inc.",\r\n1994,To the Top of the World: Adventures with Arctic Wolves,Jim Brandenburg,Walker & Company,\r\n1993,"Come Back, Salmon",Molly Cone,Sierra Club Books,\r\n1993,Talking with Artists,Pat Cummings,Bradbury Press,\r\n1992,Now Is Your Time! The African American Struggle for Freedom,Walter Dean Myers,HarperCollins,\r\n1992,Prairie Vision: The Life and Times of Solomon Butcher,Pam Conrad,HarperCollins,\r\n1991,Arctic Memories,Normee Ekoomiak,Henry Holt,\r\n1991,Seeing Earth from Space,Patricia Luber,Orchard Books,\r\n1990,The Great American Gold Rush,Rhoda Blumberg,Bradbury Press,\r\n1990,The News about Dinosaurs,Patricia Lauber,Bradbury Press,\r\n'}

In [19]:
!ls -la

total 2380
drwxr-xr-x 1 root root    4096 Apr  5 06:30  .
drwxr-xr-x 1 root root    4096 Apr  5 05:36  ..
drwxr-xr-x 4 root root    4096 Apr  2 13:31  .config
-rw-r--r-- 1 root root 2398388 Apr  5 06:17  olympics_1896_2004.csv
-rw-r--r-- 1 root root   16017 Apr  5 06:30  Orbis_Pictus_Award.csv
-rw-r--r-- 1 root root    3849 Apr  5 06:27 'Orbis Pictus Award for Outstanding Nonfiction for Children(Winner).csv'
drwxr-xr-x 1 root root    4096 Apr  2 13:31  sample_data

In [20]:
pd.read_csv("Orbis_Pictus_Award.csv")

,Year,Title,Authors,Publisher,ISBN
0,2025,Borderlands and the Mexican American Story,David Dorado Romo,Crown Books for Young Readers,NaN
1,2025,Ode to Grapefruit: How James Earl Jones Found ...,"Kari Lavelle, illustrated by Bryan Collier",Alfred A. Knopf,NaN
2,2025,Life After Whale: The Amazing Ecosystem of a W...,"Lynn Brunelle, illustrated by Jason Chin",Neal Porter Books,NaN
3,2025,Behold the Hummingbird!,"Suzanne Slade, illustrated by Thomas Gonzalez",Peachtree,NaN
4,2025,Space: The Final Pooping Frontier,"Annabeth Bondor-Stone and Connor White, illust...",Godwin Books,NaN
...,...,...,...,...,...
150,1992,Prairie Vision: The Life and Times of Solomon ...,Pam Conrad,HarperCollins,NaN
151,1991,Arctic Memories,Normee Ekoomiak,Henry Holt,NaN
152,1991,Seeing Earth from Space,Patricia Luber,Orchard Books,NaN
153,1990,The Great American Gold Rush,Rhoda Blumberg,Bradbury Press,NaN
154,1990,The News about Dinosaurs,Patricia Lauber,Bradbury Press,NaN

### Chapter 2.1: Get an overview of the data and displaying it

In [ ]:
!pip install --quiet pandas

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = pd.read_csv(filename, skiprows=5)
oo

In [22]:
# Gets a tuple representing the dimensionality of the DataFrame in the format (rows, columns)
# This dataset has: 27174 rows and 11 columns
oo.shape

(27174, 11)

In [ ]:
oo.shape?

In [24]:
# Display the first n rows (the default is 5 rows)
oo.head()

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1

In [ ]:
oo.head?

In [25]:
oo.head(3)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3

In [26]:
# Display the last 5 rows of the dataset.
oo.tail()

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
27169,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold,1
27170,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold,1
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2

In [27]:
# Display 5 randomly selected rows from the dataset
oo.sample(5)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
15144,1976,Montreal,Volleyball,Volleyball,"CHERNYSHOVA, Liudmila",URS,Women,volleyball,W,Silver,2
12109,1968,Mexico,Cycling,Cycling Track,"BOSISIO, Lorenzo",ITA,Men,Team Pursuit (4000m),M,Bronze,3
6385,1936,Berlin,Athletics,Athletics,"CUNNINGHAM, Glenn",USA,Men,1500m,M,Silver,2
6974,1936,Berlin,Equestrian,Jumping,"RANG, Henri",ROU,Men,individual,X,Silver,2
25373,2004,Athens,Aquatics,Swimming,"JEDRZEJCZAK, Otylia",POL,Women,400m freestyle,W,Silver,2

In [28]:
oo.sample(5, random_state=43)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
3203,1920,Antwerp,Shooting,Shooting,"JONSSON, Gustaf Adolf",SWE,Men,"600m free rifle, team",M,Bronze,3
8448,1952,Helsinki,Rowing,Rowing,"RODRIGUEZ, Juan A.",URU,Men,double sculls (2x),M,Bronze,3
17167,1984,Los Angeles,Basketball,Basketball,"VUKICEVIC, Branko",YUG,Men,basketball,M,Bronze,3
5761,1932,Los Angeles,Aquatics,Diving,"GALITZEN, Michael Riley",USA,Men,10m platform,M,Silver,2
20649,1992,Barcelona,Football,Football,"LAPINSKI, Tomasz",POL,Men,football,M,Silver,2

In [ ]:
oo.sample?

In [30]:
# Gives basic information about the dataset, such as the number of entries, the column names, whether the columns have any null values, and the data type.
oo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27174 entries, 0 to 27173
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Year          27174 non-null  int64
 1   City          27174 non-null  object
 2   Sport         27174 non-null  object
 3   Discipline    27174 non-null  object
 4   Athlete Name  27174 non-null  object
 5   NOC           27174 non-null  object
 6   Gender        27174 non-null  object
 7   Event         27174 non-null  object
 8   Event Gender  27174 non-null  object
 9   Medal         27174 non-null  object
 10  Position      27174 non-null  int64
dtypes: int64(2), object(9)
memory usage: 2.3+ MB

In [31]:
# Display the basic statistics of the dataset: count, mean, standard deviation, minimum, maximum, and percentile of each column
oo.describe()

               Year      Position
count  27174.000000  27174.000000
mean    1964.685803      1.992566
std       31.590396      0.817469
min     1896.000000      1.000000
25%     1936.000000      1.000000
50%     1972.000000      2.000000
75%     1992.000000      3.000000
max     2004.000000      3.000000

#### Exercise 2.1: Describe the dataset in a few sentences from the functions called above
Medal winners in the Summer Olympics in the year of 1964 to 2004.

In [32]:
# Shows the maximum number of rows in the current setting
pd.get_option("display.max_rows")

60

In [ ]:
# Setting to "None" will show all of the rows in the dataset
pd.set_option("display.max_rows", None)
oo

In [ ]:
pd.set_option("display.max_rows", 60)
oo

In [33]:
# Shows the maximum number of columns in the current setting
pd.get_option("display.max_columns")

20

In [34]:
# Shows the maximum column width in the current setting. Can set to bigger numbers if the content in the column overflows or got truncated.
pd.get_option("display.width")

80

In [35]:
pd.set_option("display.width", 100)

## Chapter 2.2: Select a Series (column)

In [ ]:
!pip install --quiet pandas

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = pd.read_csv(filename, skiprows=5)
oo.sample(3)

In [36]:
type(oo)

pandas.core.frame.DataFrame

In [37]:
# Column name is case sensitive! Using `oo["discipline"]` will not work.
oo["Discipline"]

0        Cycling Track
1        Cycling Track
2            Athletics
3            Athletics
4            Athletics
             ...
27169          Fencing
27170          Fencing
27171          Fencing
27172          Fencing
27173          Fencing
Name: Discipline, Length: 27174, dtype: object

In [38]:
type(oo["Discipline"])

pandas.core.series.Series

In [39]:
# Every time a Series is added to the DataFrame, that Series become an ATTRIBUTE of the DataFrame, so it can be called with the .<attribute_name> syntax.
oo.Discipline

0        Cycling Track
1        Cycling Track
2            Athletics
3            Athletics
4            Athletics
             ...
27169          Fencing
27170          Fencing
27171          Fencing
27172          Fencing
27173          Fencing
Name: Discipline, Length: 27174, dtype: object

In [40]:
# Display all column names
oo.columns

Index(['Year', 'City', 'Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender', 'Event',
       'Event Gender', 'Medal', 'Position'],
      dtype='object')

In [41]:
# Cannt use the dot notation if a column name has white space: oo.Athlete Name doesn't work!
oo["Athlete Name"]

0             FLAMENG, Léon
1        KOLETTIS, Georgios
2             LANE, Francis
3          SZOKOLYI, Alajos
4             BURKE, Thomas
                ...
27169    LOGOUNOVA, Tatiana
27170         SIVKOVA, Anna
27171        BOKEL, Claudia
27172       DUPLITZER, Imke
27173     HEIDEMANN, Britta
Name: Athlete Name, Length: 27174, dtype: object

In [42]:
oo.sample(3)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
11007,1964,Tokyo,Wrestling,Wrestling Gre-R,"KORMANIK, Jiri",TCH,Men,78 - 87kg (middleweight),M,Silver,2
268,1900,Paris,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"army rifle, 300m, 3 positions",M,Bronze,3
1920,1908,London,Archery,Archery,"BROOKS-KING, Reginald B.",GBR,Men,york round (100y - 80y - 60y),M,Silver,2

In [43]:
# Display unique values in the column (Series) returned in order of appearance in the dataset.
oo.Year.unique()

array([1896, 1900, 1904, 1908, 1912, 1920, 1924, 1928, 1932, 1936, 1948,
       1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004])

In [44]:
oo.Year.unique?

In [48]:
oo.Sport.unique()

array(['Cycling', 'Athletics', 'Aquatics', 'Shooting', 'Tennis',
       'Fencing', 'Weightlifting', 'Gymnastics', 'Wrestling', 'Sailing',
       'Archery', 'Basque Pelota', 'Cricket', 'Croquet', 'Rowing',
       'Football', 'Equestrian', 'Golf', 'Polo', 'Rugby', 'Tug of War',
       'Boxing', 'Roque', 'Lacrosse', 'Water Motorsports', 'Rackets',
       'Hockey', 'Jeu de paume', 'Skating', 'Modern Pentathlon',
       'Ice Hockey', 'Canoe / Kayak', 'Basketball', 'Handball', 'Judo',
       'Volleyball', 'Table Tennis', 'Baseball', 'Badminton', 'Softball',
       'Taekwondo', 'Triathlon'], dtype=object)

In [49]:
oo.sample(3)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
3231,1920,Antwerp,Sailing,Sailing,"BERNSTEN, Einar",NOR,Men,6m (rating 1907),X,Bronze,3
632,1900,Paris,Aquatics,Water polo,"LAUFRAY, Louis",FRA,Men,water polo,M,Bronze,3
10517,1960,Rome,Fencing,Fencing,"PIATKOWSKI, Andrzej Ryszard",POL,Men,sabre team,M,Silver,2

In [50]:
# Display a Series containing counts of unique values.
# Return a Series containing counts of unique values. The resulting object will be in descending order so that
# the first element is the most frequently-occurring element. Excludes NA values by default.
oo.Year.value_counts()

Year
2000    2015
2004    1998
1996    1859
1992    1705
1988    1546
1984    1459
1980    1387
1976    1305
1920    1298
1972    1185
1968    1031
1964    1010
1952     889
1956     885
1912     885
1924     884
1960     882
1936     875
1948     814
1908     804
1928     710
1932     615
1900     512
1904     470
1896     151
Name: count, dtype: int64

In [51]:
oo.Year.value_counts?

In [52]:
# Display the relative frequency instead. The proportion of all values will add up to 1.
# propotyion = # of rows the value appears / total rows
oo.Year.value_counts(normalize=True)

Year
2000    0.074152
2004    0.073526
1996    0.068411
1992    0.062744
1988    0.056893
1984    0.053691
1980    0.051041
1976    0.048024
1920    0.047766
1972    0.043608
1968    0.037941
1964    0.037168
1952    0.032715
1956    0.032568
1912    0.032568
1924    0.032531
1960    0.032457
1936    0.032200
1948    0.029955
1908    0.029587
1928    0.026128
1932    0.022632
1900    0.018842
1904    0.017296
1896    0.005557
Name: proportion, dtype: float64

## Challenge

Answer the following questions. Indicate the Pandas command where relevant.

1.   What is the time range covered in this dataset?
2.   The Olympics take place every 4 years. Why are there missing years?
3.   What are the types of medals awarded?
4.   Across all of the Olympic Games, how many Gold, Silver and Bronze medals have there been?
5.   Why are there not an equal number of Gold, Silver and Bronze medals?
6.   There are more Gold medals than Silver, and more Silver than Bronze. Why might that be?
7.   What are the different NOCs (National Olympic Committees)
8.   What does the NOC 'ZZX' represent?

In [53]:
oo.columns

Index(['Year', 'City', 'Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender', 'Event',
       'Event Gender', 'Medal', 'Position'],
      dtype='object')

In [55]:
print(f"1. The time range is from {oo.Year.min()} to {oo.Year.max()}")

1. The time range is from 1896 to 2004

In [60]:
display(oo.Year.unique())
print("2. Year 1916, 1940, and 1944 are missing because the Olympics was interrupted by World War I and World War II.")

array([1896, 1900, 1904, 1908, 1912, 1920, 1924, 1928, 1932, 1936, 1948,
       1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004])

2. Year 1916, 1940, and 1944 are missing because the Olympics was interrupted by World War I and World War II.

In [63]:
print(f"3. The types of medals awarded are: {oo.Medal.unique()}.")

3. The types of medals awarded are: ['Gold' 'Silver' 'Bronze'].

In [68]:
medal_value_counts = oo.Medal.value_counts()
display(medal_value_counts)
print(f"4. There has been {medal_value_counts.Gold} golds, {medal_value_counts.Silver} silvers, and {medal_value_counts.Bronze} bronzes.")

Medal
Gold      9181
Silver    9014
Bronze    8979
Name: count, dtype: int64

4. There has been 9181 golds, 9014 silvers, and 8979 bronzes.

In [69]:
print(f"5. When athlete ties, gold medals may be given to both.")

5. When athlete ties, gold medals may be given to both.

In [70]:
print(f"6. When athlete ties, medals may be given to all tied athletes It may be the case that more ties happened for gold medals.")

6. When athlete ties, medals may be given to all tied athletes It may be the case that more ties happened for gold medals.

In [73]:
print(f"7. The NOC values are: {oo.NOC.unique()}, which represents the country.")

7. The NOC values are: ['FRA' 'GRE' 'USA' 'HUN' 'GER' 'AUT' 'GBR' 'AUS' 'DEN' 'ZZX' 'SUI' 'IND'
 'NED' 'CAN' 'NOR' 'BEL' 'ESP' 'BOH' 'ITA' 'SWE' 'CUB' 'RU1' 'FIN' 'RSA'
 'ANZ' 'LUX' 'EST' 'BRA' 'JPN' 'TCH' 'NZL' 'ARG' 'HAI' 'POL' 'URU' 'YUG'
 'ROU' 'POR' 'EGY' 'PHI' 'IRL' 'CHI' 'MEX' 'LAT' 'TUR' 'KOR' 'PAN' 'JAM'
 'SRI' 'PER' 'PUR' 'IRI' 'TRI' 'URS' 'LIB' 'BUL' 'VEN' 'EUA' 'PAK' 'ISL'
 'BAH' 'BWI' 'GHA' 'IRQ' 'SIN' 'TPE' 'ETH' 'MAR' 'TUN' 'NGR' 'KEN' 'FRG'
 'MGL' 'GDR' 'UGA' 'CMR' 'PRK' 'COL' 'NIG' 'BER' 'THA' 'TAN' 'GUY' 'ZIM'
 'ZAM' 'CHN' 'CIV' 'DOM' 'ALG' 'SYR' 'SUR' 'CRC' 'SEN' 'AHO' 'DJI' 'ISV'
 'INA' 'EUN' 'NAM' 'IOP' 'QAT' 'ISR' 'LTU' 'CRO' 'SLO' 'MAS' 'RUS' 'UKR'
 'TGA' 'ARM' 'BLR' 'MDA' 'ECU' 'KAZ' 'AZE' 'BDI' 'SVK' 'CZE' 'UZB' 'GEO'
 'MOZ' 'HKG' 'KGZ' 'BAR' 'KSA' 'VIE' 'MKD' 'KUW' 'ERI' 'SCG' 'UAE' 'PAR'], which represents the country.

In [74]:
print("8. NOX ZZX represent 'Mixed Team', which comprised of athletes from different countries.")

8. NOX ZZX represent 'Mixed Team', which comprised of athletes from different countries.

##Solution

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

1. What is the time range covered in this dataset?

In [75]:
oo.Year.unique()

array([1896, 1900, 1904, 1908, 1912, 1920, 1924, 1928, 1932, 1936, 1948,
       1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004])

2. The Olympics take place every 4 years. Why are there missing years?
- World War 1: 1914-1918
- World War 2: 1939-1945

3. What are the types of medals awarded?

In [76]:
oo.Medal.unique()

array(['Gold', 'Silver', 'Bronze'], dtype=object)

4. Across all of the Olympics, how many Gold, Silver and Bronze medals have there been?

In [77]:
oo.Medal.value_counts()

Medal
Gold      9181
Silver    9014
Bronze    8979
Name: count, dtype: int64

5. Why are there not an equal number of Gold, Silver and Bronze medals?
- Tied results
- Team events
- Disqualifications

In [78]:
oo.head(10)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1
5,1896,Athens,Athletics,Athletics,"HOFMANN, Fritz",GER,Men,100m,M,Silver,2
6,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold,1
7,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver,2
8,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze,3
9,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold,1

6. There are more Gold medals than Silver, and more Silver than Bronze. Why might that be?

Men's 100km cycling
- https://en.wikipedia.org/wiki/Cycling_at_the_1896_Summer_Olympics_%E2%80%93_Men%27s_100_kilometres
- https://en.wikipedia.org/wiki/Aristidis_Konstantinidis

Men's 100m freestyle (1896)
- https://en.wikipedia.org/wiki/Swimming_at_the_1896_Summer_Olympics_%E2%80%93_Men%27s_100_metre_freestyle

7. What are the different NOCs (National Olympic Committees)

In [ ]:
oo.NOC.unique()

8. What does the NOC 'ZZX' represent?
- https://en.wikipedia.org/wiki/Mixed_teams_at_the_Olympics

## Chapter 2.5: Python Lists and Dictionaries

- List: can contain multiple data types and duplicates, is great for storing things in order like columns and values
- Dictionary: mapping keys to values for easy lookup

In [79]:
medals = ["Gold", "Silver", "Bronze"]
medals

['Gold', 'Silver', 'Bronze']

In [80]:
type(medals)

list

In [81]:
position = {"First": "Gold",
            "Second": "Silver",
            "Third": "Bronze"
}
position

{'First': 'Gold', 'Second': 'Silver', 'Third': 'Bronze'}

In [82]:
type(position)

dict

In [83]:
position["First"]

'Gold'

## Chapter 2.6: Rename a series (or column)

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [84]:
oo = pd.read_csv(filename, skiprows=5)
oo.sample(3)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
25045,2000,Sydney,Volleyball,Volleyball,"RODRIGUES, Karin",BRA,Women,volleyball,W,Bronze,3
7276,1948,London,Athletics,Athletics,"LABEACH, Lloyd",PAN,Men,200m,M,Bronze,3
20864,1992,Barcelona,Hockey,Hockey,"JUNGJOHANN, Caren",GER,Women,hockey,W,Silver,2

In [85]:
mapper = {"Athlete Name": "Athlete_Name",
          "Event Gender": "Event_Gender"}

In [86]:
oo.rename?

In [87]:
oo.rename(columns=mapper)

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1
...,...,...,...,...,...,...,...,...,...,...,...
27169,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold,1
27170,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold,1
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2

In [88]:
# The new name reverted back because the change wasn't applied to the dataframe. The rename() method returns a new DataFrame with the type.
oo.sample(3)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
23420,2000,Sydney,Aquatics,Swimming,"LILLHAGE, Josefin",SWE,Women,4x100m freestyle relay,W,Bronze,3
8369,1952,Helsinki,Cycling,Cycling Track,"BURGESS, Donald Christopher",GBR,Men,Team Pursuit (4000m),M,Bronze,3
15547,1980,Moscow,Judo,Judo,"LEHMANN, Karl-Heinz",GDR,Men,65 - 71kg (lightweight),M,Bronze,3

In [89]:
# Need to save the renamed columns back to itself.
oo = oo.rename(columns=mapper)
oo.sample(3)

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position
22533,1996,Atlanta,Handball,Handball,"LIM, O Kyeong",KOR,Women,handball,W,Silver,2
12443,1968,Mexico,Rowing,Rowing,"CIPOLLA, Bruno",ITA,Men,pair-oared shell with coxswain (2+),M,Gold,1
23060,1996,Atlanta,Volleyball,Volleyball,"TOFOLI, Paolo",ITA,Men,volleyball,M,Silver,2

In [90]:
oo = pd.read_csv(filename, skiprows=5).rename(columns=mapper)
oo.sample(3)

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position
6058,1932,Los Angeles,Fencing,Fencing,"LEVIS, Joseph L.",USA,Men,foil team,M,Bronze,3
14181,1976,Montreal,Shooting,Shooting,"LUSHCHIKOV, Gennadi",URS,Men,50m rifle prone (60 shots),X,Bronze,3
4879,1924,Paris,Tennis,Tennis,"DE MORPURGO, Umberto",ITA,Men,singles,M,Bronze,3

In [91]:
oo = pd.read_csv(filename, skiprows=5)
oo = oo.rename(columns={"Athlete Name": "Athlete_Name", "Event Gender": "Event_Gender"})
oo.sample(3)

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position
1534,1908,London,Shooting,Shooting,"PARMENTIER, André",FRA,Men,"free rifle, team",M,Bronze,3
7120,1936,Berlin,Gymnastics,Artistic G.,"PÖHLSEN, Paula",GER,Women,team competition,W,Gold,1
15820,1980,Moscow,Rowing,Rowing,"PINTSKUS, Ionas",URS,Men,eight with coxswain (8+),M,Bronze,3

In [92]:
oo = pd.read_csv(filename, skiprows=5)
oo.columns

Index(['Year', 'City', 'Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender', 'Event',
       'Event Gender', 'Medal', 'Position'],
      dtype='object')

In [93]:
# Can also rename the column names by modifying the .columns attribute directly
column_names = ['Year', 'City', 'Sport', 'Discipline', 'Athlete_Name', 'NOC', 'Gender',
       'Event', 'Event_Gender', 'Medal', 'Position']
oo.columns = column_names
oo.sample(3)

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position
21047,1992,Barcelona,Aquatics,Synchronized S.,"FRECHETTE, Sylvie",CAN,Women,solo,W,Gold,1
9720,1956,Melbourne / Stockholm,Gymnastics,Artistic G.,"RÖNSTRÖM, Eva",SWE,Women,"team, portable apparatus",W,Silver,2
8248,1952,Helsinki,Boxing,Boxing,"ADKINS, Charles",USA,Men,60 - 63.5kg (light-welterweight),M,Gold,1

In [94]:
oo = pd.read_csv(filename, skiprows=5)
oo.sample(3)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
20391,1992,Barcelona,Basketball,Basketball,"ZHIRKO, Elena",EUN,Women,basketball,W,Gold,1
986,1904,St Louis,Lacrosse,Lacrosse,"JAMIESON, Benjamin",CAN,Men,lacrosse,M,Gold,1
6006,1932,Los Angeles,Athletics,Athletics,"JÄRVINEN, Akiles Eero Johannes",FIN,Men,decathlon,M,Silver,2

In [95]:
pd.read_csv?

In [96]:
# The `name` parameter in pd.read_csv() specify the sequence of column names that should be applied to
# the dataset.
# If the data already has a column name row, will need to set header=0 first so that the first row becomes
# the column, then it will be overriden by the `names` parameter.

oo = pd.read_csv(filename, skiprows=5, names=column_names)
oo.head()

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position
0,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
1,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
2,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
3,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
4,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3

In [97]:
oo = pd.read_csv(filename, skiprows=5, names=column_names, header=0)
oo.head()

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1

## Chapter 2.7: Remove a Series (column) or row
What if some columns are not relevant?

Note: In pandas, row is axis 0, and column is axis 1.

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [98]:
oo = pd.read_csv(filename, skiprows=5)
oo.sample(3)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
24101,2000,Sydney,Shooting,Shooting,"RHODE, Kimberly",USA,Women,double trap (120 targets),W,Bronze,3
19141,1988,Seoul,Hockey,Hockey,"BUTER, Yvonne",NED,Women,hockey,W,Bronze,3
23895,2000,Sydney,Cycling,Cycling Track,"MATVEYEV, Sergiy",UKR,Men,Team Pursuit (4000m),M,Silver,2

In [99]:
# We don't actually need the 'Position' column because we already have the 'Medal' column.
# Specify `axis=1` so that pandas know we're draopping an column.
oo.drop('Position', axis=1)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
...,...,...,...,...,...,...,...,...,...,...
27169,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold
27170,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver

In [ ]:
# Specifying the axis wrongly will cause an error because 'Position' is a column.
# oo.drop('Position', axis=0)

In [100]:
oo.sample(3)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
26196,2004,Athens,Rowing,Rowing,"DEAKIN, Matt",USA,Men,eight with coxswain (8+),M,Gold,1
10870,1964,Tokyo,Athletics,Athletics,"ARDEN, Daphne",GBR,Women,4x100m relay,W,Bronze,3
15661,1980,Moscow,Canoe / Kayak,Canoe / Kayak F,"PARFENOVICH, Vladimir",URS,Men,K-2 500m (kayak double),M,Gold,1

In [101]:
# drop() returns a new DataFrame, so you'll have to save the new DataFrame back to oo.
oo = oo.drop('Position', axis=1)
oo.sample(3)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
4058,1920,Antwerp,Tug of War,Tug of War,"THORNE, Ernest Arthur",GBR,Men,tug of war,M,Gold
7231,1948,London,Athletics,Athletics,"SCHWAB, Erich Arthur Fritz",SUI,Men,10000m walk,M,Bronze
6446,1936,Berlin,Athletics,Athletics,"LEICHUM, Wilhelm",GER,Men,4x100m relay,M,Bronze

In [102]:
oo = pd.read_csv(filename, skiprows=5).drop('Position', axis=1)
oo.sample(3)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
26419,2004,Athens,Handball,Handball,"SPREM, Goran",CRO,Men,handball,M,Gold
25771,2004,Athens,Wrestling,Wrestling Free.,"TAYMAZOV, Artur",UZB,Men,96 - 120kg,M,Gold
24952,2000,Sydney,Gymnastics,Artistic G.,"PERESHKURA, Valeriy",UKR,Men,team competition,M,Silver

In [103]:
# For readability, if you want to chain multiple methods, we can use the dot notation on different lines
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
15730,1980,Moscow,Basketball,Basketball,"JERKOV, Zeljko",YUG,Men,basketball,M,Gold
16515,1980,Moscow,Volleyball,Volleyball,"KHRISTOLOVA, Anka",BUL,Women,volleyball,W,Bronze
5694,1928,Amsterdam,Aquatics,Water polo,"TRIBOUILLET, Achille C. M.",FRA,Men,water polo,M,Bronze

In [104]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
19016,1988,Seoul,Handball,Handball,"LAVROV, Andrey",URS,Men,handball,M,Gold
16589,1980,Moscow,Fencing,Fencing,"LIS, Andrzej",POL,Men,épée team,M,Silver
1481,1908,London,Rowing,Rowing,"MORIMONT, Marcel",BEL,Men,eight with coxswain (8+),M,Silver

In [105]:
oo = pd.read_csv(filename, skiprows=5)
oo.drop('Position', axis=1, inplace=True)   # --> using `inplace=True` applies the change to the original DataFrame
oo.sample(3)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
12723,1972,Munich,Weightlifting,Weightlifting,"MANG, Rudolf",FRG,Men,"+ 110kg, total (super heavyweight)",M,Silver
25156,2000,Sydney,Fencing,Fencing,"LOYOLA, Nelson",CUB,Men,épée team,M,Bronze
20463,1992,Barcelona,Badminton,Badminton,"GUAN, Weizhen",CHN,Women,doubles,W,Silver

In [106]:
# `inplace=True` argument doesn't allow for chaining because it returns None type, so the next method cannot be applied.

oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1, inplace=True)
)
oo.sample(3)

AttributeError: 'NoneType' object has no attribute 'sample'

In [ ]:
oo.drop?

In [107]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
3802,1920,Antwerp,Equestrian,Eventing,"BONVALET, Jules",BEL,Men,team,X,Bronze
9417,1956,Melbourne / Stockholm,Football,Football,"MASLENKIN, Anatoli",URS,Men,football,M,Gold
22189,1996,Atlanta,Table Tennis,Table Tennis,"YOO, Nam-Kyu",KOR,Men,doubles,M,Bronze

In [108]:
oo.head(3)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze

In [109]:
# To drop a row, specify the index of the row in the argument and set `axis=0`.
# Notice that the new index doesn't readjust!
oo = (pd.read_csv(filename, skiprows=5)
      .drop(2, axis=0)
)
oo.head(3)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3

In [110]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop([0, 1, 3], axis=0)
)
oo.head(3)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1
5,1896,Athens,Athletics,Athletics,"HOFMANN, Fritz",GER,Men,100m,M,Silver,2

In [111]:
oo = oo.drop(['City', 'Sport'], axis=1)
oo.head(3)

   Year Discipline    Athlete Name  NOC Gender Event Event Gender   Medal  Position
2  1896  Athletics   LANE, Francis  USA    Men  100m            M  Bronze         3
4  1896  Athletics   BURKE, Thomas  USA    Men  100m            M    Gold         1
5  1896  Athletics  HOFMANN, Fritz  GER    Men  100m            M  Silver         2

In [112]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
6020,1932,Los Angeles,Rowing,Rowing,"EASTWOOD, Earl",CAN,Men,eight with coxswain (8+),M,Bronze
8876,1952,Helsinki,Aquatics,Water polo,"VIZVARI, György",HUN,Men,water polo,M,Gold
10603,1960,Rome,Athletics,Athletics,"GORYAEV, Vladimir",URS,Men,triple jump,M,Silver

In [113]:
pd.merge?

In [114]:
pd.concat?

In [115]:
oo.groupby?

## Chapter 2.8: Filtering rows for a single condition

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

In [ ]:
type(True)

In [ ]:
type(False)

In [ ]:
oo.Year.dtype

In [ ]:
first_olympics = (oo.Year == 1896)
first_olympics

In [ ]:
oo[first_olympics]

In [ ]:
oo[oo.Year == 1896]

In [ ]:
oo[oo.Year < 1896]

In [ ]:
oo[(oo.Year <= 1896)]

## Filter rows for multiple conditions

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.tail(3)

In [ ]:
oo.dtypes

In [ ]:
oo[oo.City == 'Athens']

In [ ]:
#oo[oo.City == Athens]

In [ ]:
oo[(oo.Year == 1896) | (oo.Year == 2004)]

In [ ]:
oo[(oo.City == 'Athens') & (oo.Year == 2004)]

In [ ]:
oo[(oo.City == 'Athens') & ~(oo.Year == 1896)]

In [ ]:
first_men_100m = oo[(oo.Year == 1896) & (oo.Gender == 'Men') & (oo.Event == '100m')]
first_men_100m

In [ ]:
oo[(oo.Year == 1896) & (oo.Gender == 'Men') & (oo.Event == '100m')][["Year", "Athlete Name", "NOC", "Event", "Medal"]]

In [ ]:
first_men_100m[["Year", "Athlete Name", "NOC", "Event", "Medal"]]

## Using String methods

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.head(3)

In [ ]:
oo["Athlete Name"].str.lower()

In [ ]:
oo.Event.unique()

In [ ]:
oo.Event.str.capitalize()

In [ ]:
oo.Event = oo.Event.str.capitalize()
oo.Event.unique()

In [ ]:
dir(oo.Event.str)

In [ ]:
oo["Athlete Name"].str.contains("Latynina")

In [ ]:
# Larisa Latynina - most decorated Female athlete
oo[oo["Athlete Name"].str.contains("Latynina")]

In [ ]:
oo[oo["Athlete Name"].str.contains("LATYNINA")]

In [ ]:
dir(oo.Event.str)

In [ ]:
oo.City = oo.City.str.upper()
oo.sample(3)

In [ ]:
oo.City.unique()

## Sorting a DataFrame or Series

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

In [ ]:
oo["Athlete Name"].sort_values()

In [ ]:
type(oo["Athlete Name"].sort_values())

In [ ]:
oo.sort_values("Athlete Name")

In [ ]:
type(oo.sort_values("Athlete Name"))

In [ ]:
oo.head(3)

In [ ]:
oo.sort_values("Athlete Name", ascending=False)

In [ ]:
oo.sort_values("Athlete Name", ascending=False).head(25)

In [ ]:
oo.sort_values(by=['Year','Athlete Name'])

In [ ]:
oo.sort_values(by=["Year", "Athlete Name"], ascending=[False, True])

In [ ]:
oo.head(7)

In [ ]:
oo.sort_values(by=["Year", "Event", "Medal"], ascending=[True, True, False]).head(7)

In [ ]:
oo.dtypes

## Working with data types (dtype)

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

In [ ]:
oo.dtypes

In [ ]:
oo.Medal.unique()

In [ ]:
oo.Medal = oo.Medal.astype("category")
oo.dtypes

In [ ]:
oo.Gender.unique()

In [ ]:
oo['Event Gender'].unique()

In [ ]:
oo.Gender = oo.Gender.astype("category")
oo['Event Gender'] = oo['Event Gender'].astype("category")
oo.dtypes

In [ ]:
oo.Medal.astype("category")

In [ ]:
pd.Categorical?

In [ ]:
medal_order = ["Bronze", "Silver", "Gold"]
pd.Categorical(oo.Medal, categories=medal_order, ordered=True)

In [ ]:
oo.Medal = pd.Categorical(oo.Medal, categories=medal_order, ordered=True)
oo.dtypes

In [ ]:
oo.Medal

In [ ]:
oo.sort_values(by=["Year", "Event", "Medal"], ascending=[True, True, False]).head(7)

## Memory usage of different dtypes

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
df = pd.read_csv(filename, skiprows=5)
df.dtypes

In [ ]:
oo.dtypes

In [ ]:
oo.Medal.memory_usage?

In [ ]:
print(f"Medal series memory usage using dtype category: {oo.Medal.memory_usage(deep=True)}")
print(f"Medal series memory usage using dtype object: {df.Medal.memory_usage(deep=True)}")

In [ ]:
oo.Medal.memory_usage(deep=True) / df.Medal.memory_usage(deep=True)

In [ ]:
print(f"Gender series memory usage using dtype category: {oo.Gender.memory_usage(deep=True)}")
print(f"Gender series memory usage using dtype object: {df.Gender.memory_usage(deep=True)}")
print(f"Gender series memory usage using dtype category: {oo['Event Gender'].memory_usage(deep=True)}")
print(f"Gender series memory usage using dtype object: {df['Event Gender'].memory_usage(deep=True)}")

In [ ]:
oo.City.astype("string")

In [ ]:
oo.sample(2)

In [ ]:
oo.dtypes

In [ ]:
oo.City = oo.City.astype("string")
oo.Sport = oo.Sport.astype("string")
oo.Discipline = oo.Discipline.astype("string")
oo["Athlete Name"] = oo["Athlete Name"].astype("string")
oo.NOC = oo.NOC.astype("string")
oo.Event = oo.Event.astype("string")
oo.dtypes

In [ ]:
oo.City.dtype

In [ ]:
df.City.dtype

In [ ]:
print(f"City series memory usage using dtype string: {oo.City.memory_usage(deep=True)}")
print(f"City series memory usage using dtype object: {df.City.memory_usage(deep=True)}")

## Defining dtypes when you read in a file

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

In [ ]:
oo.dtypes

In [ ]:
dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": "category"}

dtype_mapper

In [ ]:
pd.api.types.CategoricalDtype?

In [ ]:
ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
ordered_medals

In [ ]:
dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}

dtype_mapper

In [ ]:
oo = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
oo.sample(3)

In [ ]:
oo.dtypes

In [ ]:
oo["Event Gender"].unique()

In [ ]:
oo = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
oo['Event Gender'] = oo['Event Gender'].astype("category")
oo.dtypes

## Python Functions

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def show_df(filename="olympics_1896_2004.csv"):
  """Read in csv file and display DataFrame"""
  df = pd.read_csv(filename, skiprows=5)
  return df

show_df()

In [ ]:
type(show_df())

In [ ]:
ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}

dtype_mapper

In [ ]:
oo = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
      .drop('Position', axis=1)
)
oo.sample(3)

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )

  return df

preprocess()

In [ ]:
preprocess()

In [ ]:
oo = preprocess()
oo.sample(3)

In [ ]:
oo.dtypes

In [ ]:
oo["Event Gender"].unique()

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  return df

oo = preprocess()
oo.sample(3)

In [ ]:
oo.dtypes

## Working with Indexes

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  return df

oo = preprocess()
oo.head(5)

In [ ]:
oo.index

In [ ]:
oo.columns

In [ ]:
oo.shape

In [ ]:
pd.read_csv(filename, skiprows=5, header=None).head()

In [ ]:
oo = preprocess()
oo.head(5)

In [ ]:
oo[oo['Athlete Name'].str.contains("LEWIS, Carl")]

In [ ]:
oo.loc[22719, "Event"]

In [ ]:
oo = oo.set_index("Athlete Name")
oo.head(5)

In [ ]:
oo.index

In [ ]:
oo.loc["LEWIS, Carl", "Event"]

In [ ]:
oo.head(3)

In [ ]:
oo.columns

In [ ]:
oo.shape

In [ ]:
oo.head(3)

In [ ]:
oo.loc["LEWIS, Carl", ["Year", "Event", "Medal"]]

In [ ]:
oo.loc["LEWIS, Carl", :]

In [ ]:
oo.loc["LEWIS, Carl"]

In [ ]:
oo = oo.sort_index()
oo.head(3)

In [ ]:
oo = oo.reset_index()
oo.head(3)

In [ ]:
oo.iloc[0, 0]

In [ ]:
oo.iloc[0, 5]

In [ ]:
oo.iloc[0, :]

In [ ]:
oo.iloc[0]

## Being Productive in pandas - My Best Practices

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  return df

oo = preprocess()
oo.sample(3)

**Get immediate feedback**

In [ ]:
oo = preprocess()

In [ ]:
oo.sample(3)

In [ ]:
oo = preprocess()
oo.sample(3)

**Understand the basics of Python**

In [ ]:
dir(pd)

In [ ]:
[func.upper() for func in dir(pd)]

**Searching for method names**

In [ ]:
import re
import pandas as pd

search_string = "excel"

[func for func in dir(pd) if re.search(rf"{search_string}", func, re.IGNORECASE)]

In [ ]:
pd.read_excel?

In [ ]:
[func
 for func in dir(pd)
 if re.search(rf"{search_string}", func, re.IGNORECASE)]

**Documentation while staying in the IDE**

In [ ]:
pd.read_excel?

**head() vs. sample()**

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

**Functions to preprocess data. Modify the data, not the original files**

In [ ]:
def preprocess(filename):
  """Transform the data. Change the dataframe and not the original csv files"""
  ...

preprocess(filename)

**Using python assert**

In [ ]:
oo[(oo.Year < 1896) & (oo.Year > 2004)].shape

In [ ]:
oo[(oo.Year < 1896) & (oo.Year > 2004)].shape[0] == 0

In [ ]:
assert(oo[(oo.Year < 1896) & (oo.Year > 2004)].shape[0] == 0)

In [ ]:
assert(oo[(oo.Year < 1896) & (oo.Year > 2004)].shape[0] == 0)
print("All tests passed")

In [ ]:
#assert(oo[(oo.Year < 1896) & (oo.Year > 2004)].shape[0] == (0, 10))
#print("All tests passed")

**Chaining and splitting over several rows. No inplace=True**

In [ ]:
oo = pd.read_csv(filename, skiprows=5)
oo = oo.drop('Position', axis=1)
oo.head(3)

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.head(3)

In [ ]:
last3 = pd.read_csv(filename, skiprows=5).sort_values(['Year', 'Athlete Name']).tail(3)
last3

In [ ]:
last3 = (pd.read_csv(filename, skiprows=5)
        .sort_values(['Year', 'Athlete Name'])
        .tail(3)
)
last3

In [ ]:
last3 = (pd.read_csv(filename, skiprows=5)
#        .sort_values(['Year', 'Athlete Name'])
        .tail(3)
)
last3

**isin()**

In [ ]:
oo.Year.isin?

In [ ]:
years_of_interest = [1972, 1980, 1984, 1992, 2000, 2004]

In [ ]:
oo[oo.Year.isin(years_of_interest)]

In [ ]:
oo[~oo.Year.isin(years_of_interest)]

**Finding and dealing with missing values**

In [ ]:
oo.info()

## Creating Series and DataFrames

In [ ]:
import pandas as pd

In [ ]:
city = ["London", "Rio", "Tokyo"]
start_date = ["27th Jul, 2012", "5th Aug, 2016", "23rd July, 2021"]

In [ ]:
pd.Series(city)

In [ ]:
pd.DataFrame({"City": pd.Series(city),
              "Start Date": pd.Series(start_date)})

In [ ]:
pd.DataFrame({"City": city,
              "Start Date": start_date})

In [ ]:
pd.DataFrame(zip(city, start_date))

In [ ]:
pd.DataFrame(zip(city, start_date), columns=["City", "Start Date"])

## Working with dates

In [ ]:
import pandas as pd

In [ ]:
city = ["London", "Rio", "Tokyo"]
start_date = ["07-27-2012", "5th Aug, 2016", "23rd Jul, 2021"]
end_date = ["12th Aug, 2012", "21-08-2016", "8th Aug, 2021"]

In [ ]:
games = pd.DataFrame(zip(city, start_date, end_date), columns=["City", "Start Date", "End Date"])
games

In [ ]:
games.dtypes

In [ ]:
import re
import pandas as pd

search_string = "date"

[func for func in dir(pd) if re.search(rf"{search_string}", func, re.IGNORECASE)]

In [ ]:
pd.to_datetime?

In [ ]:
#pd.to_datetime(games["Start Date"])

In [ ]:
pd.to_datetime(games["Start Date"], format='mixed')

In [ ]:
games["Start Date"] = pd.to_datetime(games["Start Date"], format='mixed')
games["End Date"] = pd.to_datetime(games["End Date"], format='mixed')
games["City"] = games.City.astype("string")
games

In [ ]:
games.dtypes

In [ ]:
games["End Date"]

In [ ]:
games["Start Date"]

In [ ]:
games["End Date"] - games["Start Date"]

In [ ]:
games = games.assign(duration=games["End Date"] - games["Start Date"])
games

In [ ]:
games.dtypes

## Combining DataFrames

In [ ]:
import pandas as pd

In [ ]:
start = pd.DataFrame({"city": ["London", "Rio", "Tokyo"],
                      "start_date": ["27th Jul, 2012", "5th Aug, 2016", "23rd July, 2021"]})
start

In [ ]:
end = pd.DataFrame({"City": ["London", "Tokyo", "Paris"],
                    "end_date": ["12th Aug, 2012", "8th Aug, 2021", "11th Aug, 2024"]})
end

In [ ]:
pd.concat?

In [ ]:
pd.concat([start, end], axis=0)

In [ ]:
end = pd.DataFrame({"city": ["London", "Tokyo", "Paris"],
                    "end_date": ["12th Aug, 2012", "8th Aug, 2021", "11th Aug, 2024"]})
end

In [ ]:
pd.concat([start, end], axis=0)

In [ ]:
pd.concat([start, end], axis=1)

**Inner join**

In [ ]:
start

In [ ]:
end

In [ ]:
pd.merge?

In [ ]:
pd.merge(left=start, right=end, on="city", how="inner")

**Outer join**

In [ ]:
start

In [ ]:
end

In [ ]:
pd.merge(left=start, right=end, on="city", how="outer")

**Left join**

In [ ]:
start

In [ ]:
pd.merge(left=start, right=end, on="city", how="left")

**Right join**

In [ ]:
end

In [ ]:
pd.merge(left=start, right=end, on="city", how="right")

## Combining Datasets

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  return df

preprocess()

In [ ]:
oo = preprocess()
oo.sample(3)

In [ ]:
!wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

In [ ]:
new_filename =  "olympics_2008.csv"
nw = pd.read_csv(new_filename)
nw.head(5)

In [ ]:
oo.sample(3)

In [ ]:
pd.concat([oo, nw], axis=0)

In [ ]:
nw.columns

In [ ]:
oo.columns

In [ ]:
nw.columns = ['City', 'Edition', 'Sport', 'Discipline', 'Athlete', 'Country_code',
       'Gender', 'Event', 'Event_gender', 'Medal', 'Result']
nw.columns

In [ ]:
new_columns = ['City', 'Edition', 'Sport', 'Discipline', 'Athlete', 'Country_code',
       'Gender', 'Event', 'Event_gender', 'Medal', 'Result']

In [ ]:
nw = pd.read_csv(new_filename, names=new_columns)
nw.columns

In [ ]:
nw.columns = [column.capitalize() for column in nw.columns]
nw.columns

In [ ]:
pd.concat([oo, nw], axis=0)

In [ ]:
oo.columns

In [ ]:
nw.columns

In [ ]:
nw.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']

In [ ]:
pd.concat([oo, nw], axis=0)

In [ ]:
nw.Result.unique()

In [ ]:
nw = nw.drop("Result", axis=1)
nw.sample(3)

In [ ]:
pd.concat([oo, nw], axis=0)

In [ ]:
pd.concat([oo, nw], axis=0).dtypes

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  return df

nw = preprocess_2008()
nw.sample(3)

## Working with Missing Data

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw.info()

In [ ]:
import re

search_string = "na"

[func for func in dir(nw.City) if re.search(rf"{search_string}$", func, re.IGNORECASE)]

In [ ]:
nw.City.isna?

In [ ]:
nw.City.isna()

In [ ]:
nw.City.isna().sum()

In [ ]:
nw[nw.City.isna()]

In [ ]:
nw.City.unique()

In [ ]:
nw.shape

In [ ]:
import re

search_string = "na"

[func for func in dir(nw.City) if re.search(rf"{search_string}$", func, re.IGNORECASE)]

In [ ]:
nw.City.fillna?

In [ ]:
nw.City = nw.City.fillna(value="Beijing")
nw.City.unique()

In [ ]:
nw.Year

In [ ]:
nw.Year.unique()

In [ ]:
nw.Year = nw.Year.fillna(value=2008)
nw.info()

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  return df

nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw.dtypes

## Removing Missing Data

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  return df

nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw.info()

In [ ]:
nw[nw.Sport.isna()]

In [ ]:
nw.dropna(how="all", axis=0)

In [ ]:
nw.dropna(how="any", axis=0)

In [ ]:
nw[nw.Sport.isna()]

In [ ]:
nw.dropna?

In [ ]:
nw.columns

In [ ]:
nw.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")

In [ ]:
nw = nw.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
nw.info()

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  return df

nw = preprocess_2008()
nw.sample(3)

##Working with Duplicates

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  return df

nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw.shape

In [ ]:
nw.duplicated?

In [ ]:
nw.duplicated()

In [ ]:
nw.duplicated().sum()

In [ ]:
nw.loc[nw.duplicated(), :]

In [ ]:
nw.shape

In [ ]:
nw = nw.drop_duplicates()
nw.shape

In [ ]:
nw.columns

In [ ]:
athlete_multiple_events = nw.duplicated(subset=['Athlete Name', 'NOC', 'Gender'])
athlete_multiple_events

In [ ]:
nw.duplicated?

In [ ]:
nw.loc[athlete_multiple_events, :]

In [ ]:
nw.loc[athlete_multiple_events, :].sort_values("Athlete Name")

In [ ]:
nw.loc[nw["Athlete Name"] == "ZOU, Kai"]

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  return df

nw = preprocess_2008()
nw.sample(3)

## Validating data

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  return df

oo = preprocess()

def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  return df

nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw["Event Gender"].unique()

In [ ]:
nw.Gender.unique()

In [ ]:
nw.loc[(nw["Event Gender"] == "M") & (nw.Gender != "Men")]

In [ ]:
nw.loc[(nw["Event Gender"] == "F") & (nw.Gender != "Women")]

In [ ]:
nw.loc[(nw.Gender == "Women") & ((nw["Event Gender"] != "W") & (nw["Event Gender"] != "X"))]

In [ ]:
nw.loc[(nw.Gender == "Men") & ((nw["Event Gender"] != "M") & (nw["Event Gender"] != "X"))]

In [ ]:
oo["Event Gender"].unique()

In [ ]:
oo.Gender.unique()

In [ ]:
oo.loc[(oo["Event Gender"] == "M") & (oo.Gender != "Men")]

In [ ]:
oo.loc[(oo["Event Gender"] == "F") & (oo.Gender != "Women")]

In [ ]:
oo.loc[(oo.Gender == "Women") & ((oo["Event Gender"] != "W") & (oo["Event Gender"] != "X"))]

In [ ]:
oo.loc[(oo.Gender == "Men") & ((oo["Event Gender"] != "M") & (oo["Event Gender"] != "X"))]

In [ ]:
oo.loc[(oo.Year == 2000) & (oo.Event == "marathon")]

In [ ]:
oo.loc[24676, "Gender"] = "Women"
oo.loc[(oo.Year == 2000) & (oo.Event == "marathon")]

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  return df

oo = preprocess()
oo.sample(3)

In [ ]:
oo.dtypes

In [ ]:
nw.Year.unique()

In [ ]:
nw.City.unique()

In [ ]:
nw["Event Gender"].unique()

In [ ]:
nw["Event Gender"].unique().tolist()

In [ ]:
oo["Event Gender"].unique().tolist()

In [ ]:
nw["Event Gender"].unique().tolist() == oo["Event Gender"].unique().tolist()

In [ ]:
sorted(nw["Event Gender"].unique().tolist())

In [ ]:
sorted(oo["Event Gender"].unique().tolist())

In [ ]:
assert(sorted(nw["Event Gender"].unique().tolist()) == sorted(oo["Event Gender"].unique().tolist()))
print("Passes all tests ...")

In [ ]:
#assert(sorted(nw["Event Gender"].unique().tolist()) == sorted(oo["Event Gender"].unique().tolist()))
#assert(sorted(nw.Gender.unique().tolist()) == sorted(oo.Gender.unique().tolist()))
#assert(sorted(nw.Medal.unique().tolist()) == sorted(oo.Medal.unique().tolist()))
#print("Passes all tests ...")

In [ ]:
sorted(oo.Medal.unique().tolist())

In [ ]:
sorted(nw.Medal.unique().tolist())

In [ ]:
nw.Medal.str.capitalize()

In [ ]:
nw.Medal = nw.Medal.str.capitalize()
nw.sample(3)

In [ ]:
assert(sorted(nw["Event Gender"].unique().tolist()) == sorted(oo["Event Gender"].unique().tolist()))
assert(sorted(nw.Gender.unique().tolist()) == sorted(oo.Gender.unique().tolist()))
assert(sorted(nw.Medal.unique().tolist()) == sorted(oo.Medal.unique().tolist()))
print("Passes all tests ...")

In [ ]:
sorted(nw.Sport.unique().tolist())

In [ ]:
sorted(oo.Sport.unique().tolist())

In [ ]:
nw.NOC.unique()

In [ ]:
nw.Sport = nw.Sport.str.lower()
nw.Discipline = nw.Discipline.str.lower()
nw.Event = nw.Event.str.lower()
nw.NOC = nw.NOC.str.upper()
nw.sample(3)

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  return df

nw = preprocess_2008()
nw.sample(3)

## Further Data Validation

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  return df

oo = preprocess()

def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  return df

nw = preprocess_2008()
nw.sample(3)

In [ ]:
medals = ['Gold', 'Silver', 'Bronze', 'Bronze', 'Gold']
medals

In [ ]:
medals[0]

In [ ]:
medals[1]

In [ ]:
len(medals)

In [ ]:
nw["Athlete Name"]

In [ ]:
import re

search_string = "split"

[func for func in dir(nw["Athlete Name"].str) if re.search(rf"{search_string}", func, re.IGNORECASE)]

In [ ]:
nw["Athlete Name"].str.split?

In [ ]:
nw["Athlete Name"].str.split(", ")

In [ ]:
nw["Athlete Name"].str.split(", ").tolist()

In [ ]:
athlete_names = nw["Athlete Name"].str.split(", ").tolist()
athlete_names

In [ ]:
import re

search_string = "upper"

[func for func in dir(nw["Athlete Name"].str) if re.search(rf"{search_string}", func, re.IGNORECASE)]

In [ ]:
[athlete_name for athlete_name in athlete_names]

In [ ]:
[athlete_name[0] for athlete_name in athlete_names]

In [ ]:
[athlete_name[0].isupper() for athlete_name in athlete_names]

In [ ]:
len([item[0].isupper() for item in athlete_names])

In [ ]:
nw.info()

##Updating the dtypes

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  return df

oo = preprocess()
nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw.dtypes

In [ ]:
oo.dtypes

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw.dtypes

## Combine the datasets

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

In [ ]:
oo = preprocess()
oo.sample(3)

In [ ]:
oo.dtypes

In [ ]:
nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw.dtypes

In [ ]:
pd.concat([oo, nw])

In [ ]:
pd.concat([oo, nw]).dtypes

In [ ]:
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
up.dtypes

##Plotting data

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt


if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df


def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
import matplotlib.pyplot as plt

**For the first Olympics, how many events were there for each of the different sports? Plot them using different graphs.**

In [ ]:
first_games = up[up.Year == 1896]
first_games

In [ ]:
first_games.Sport.value_counts()

In [ ]:
first_games.Sport.value_counts().plot?

In [ ]:
type(first_games.Sport.value_counts())

In [ ]:
dir(pd.Series)

In [ ]:
pd.Series.plot?

In [ ]:
first_games.Sport.value_counts().plot(kind='line')

In [ ]:
first_games.Sport.value_counts().plot(figsize=(10,3))

In [ ]:
(first_games
 .Sport
 .value_counts()
 .plot(figsize=(10,3))
)

In [ ]:
(first_games
 .Sport
 .value_counts()
 #.plot(figsize=(10,3))
)

In [ ]:
(first_games
 .Sport
 .value_counts()
 .plot(kind='bar')
)

In [ ]:
(first_games
 .Sport
 .value_counts()
 .plot
 .bar()
)

In [ ]:
(first_games
 .Sport
 .value_counts()
 .plot(kind='barh')
)

In [ ]:
(first_games
 .Sport
 .value_counts()
 .plot(kind='barh', color='red')
)

In [ ]:
(first_games
 .Sport
 .value_counts()
 .plot(kind='barh', color=['blue', 'red'])
)

##Working with colormaps and Seaborn

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
games_2008 = up[up.Year == 2008]
games_2008.sample(3)

In [ ]:
(games_2008
 .Medal
 .value_counts())

In [ ]:
import seaborn as sns

In [ ]:
plt.figure(figsize=(5,3))
plt.title("Medals from the 2008 games")
sns.countplot(data=games_2008,
              x='Medal',
              )

In [ ]:
plt.figure(figsize=(5,3))
plt.title("Medals from the 2008 games")
sns.countplot(data=games_2008,
              x='Medal',
              order=["Gold", "Silver", "Bronze"])

In [ ]:
plt.figure(figsize=(5,3))
plt.title("Medals from the 2008 games")
sns.countplot(data=games_2008,
              x='Medal',
              order=["Gold", "Silver", "Bronze"],
              hue='Gender')

In [ ]:
plt.figure(figsize=(5,3))
plt.title("Medals from the 2008 games")
sns.countplot(data=games_2008,
              x='Medal',
              order=["Gold", "Silver", "Bronze"],
              hue='Gender',
              palette='seismic')

In [ ]:
plt.figure(figsize=(5,3))
plt.title("Medals from the 2008 games")
sns.countplot(data=games_2008,
              x='Medal',
              order=["Gold", "Silver", "Bronze"],
              hue='Gender',
              palette='coolwarm')

In [ ]:
plt.figure(figsize=(5,3))
plt.title("Medals from the 2008 games")
sns.countplot(data=games_2008,
              x='Medal',
              order=["Gold", "Silver", "Bronze"],
              hue='Gender',
              palette='bwr')

In [ ]:
plt.figure(figsize=(5,3))
plt.title("Medals from the 2008 games")
sns.countplot(data=games_2008,
              x='Medal',
              order=["Gold", "Silver", "Bronze"],
              hue='Gender',
              palette='bwr_r')

##Working with groupby

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt


if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
sprints = up[(up.Year == 2008) & ((up.Event == '100m') | (up.Event == '200m'))]
sprints

In [ ]:
sp = sprints.groupby(['NOC', 'Gender', 'Event'])
sp

In [ ]:
up.groupby("Year")

In [ ]:
type(up.groupby('Year'))

In [ ]:
up.groupby("Year").count()

In [ ]:
for group_key, group_value in up.groupby('Year'):
    print(group_key)
    print(group_value)

In [ ]:
type(group_value)

In [ ]:
up.groupby(['Year']).count()

In [ ]:
up.groupby("Year").size()

In [ ]:
up.groupby(['Year','NOC']).count()

In [ ]:
up.groupby(['Year','NOC'])['Medal'].count()

In [ ]:
up.groupby(['Year','NOC']).size()

In [ ]:
up.groupby(['Year','NOC','Medal']).size()

In [ ]:
up.groupby(['NOC'])['Year'].min()

In [ ]:
up.groupby(['NOC'])['Year'].max()

In [ ]:
up.groupby(['NOC'])['Year'].min()

In [ ]:
up.groupby(['NOC'])['Year'].agg(['min', 'max', 'count'])

##Reshaping data: Stacking, Unstacking and MultiIndex

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt


if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
  df = df.drop('Position', axis=1)
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
sprints = up[(up.Year == 2008) & ( (up.Event == '100m') | (up.Event == '200m'))]
sprints

In [ ]:
sp = sprints.groupby(['NOC','Gender','Event']).size()
sp

In [ ]:
sp.unstack?

In [ ]:
sp.unstack('Gender', fill_value=0)

In [ ]:
(sp
 .unstack('Gender', fill_value=0)
 .unstack('Event', fill_value=0)
)

In [ ]:
sp.unstack?

In [ ]:
sp.unstack(['Gender', 'Event'], fill_value=0)

In [ ]:
sp = sprints.groupby(['NOC','Gender','Event']).size()
sp

In [ ]:
sp.unstack(level=1, fill_value=0)

In [ ]:
sprints_table = sp.unstack(level=1, fill_value=0).unstack(level=1, fill_value=0)
sprints_table

In [ ]:
sprints_NOC = sprints_table.stack("Gender")
sprints_NOC

In [ ]:
sprints_NOC.index

In [ ]:
sprints_NOC.loc[('JAM',   'Men'), :]

In [ ]:
sprints_NOC.loc[('JAM',   'Men'), '100m']

In [ ]:
sprints_NOC.iloc[0, :]

In [ ]:
sprints_NOC.iloc[0, 0]

In [ ]:
sprints_NOC.stack?

In [ ]:
sprints_NOC.unstack?

## Challenge

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
  df = df.drop('Position', axis=1)
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

**Using a line graph, plot the number of gold medals won by the USA male and female Olympians throughout the history of the Olympics?
Distinguish between the male and female Olympians in the line graph using blue and pink**

**Using a bar chart, plot the 5 Olympians who have won the most gold medals from the dataset (1896 to 2008). When there is a tie, consider the number of silver medals, then bronze medals.**

##Solution

**Using a line graph, plot the number of gold medals won by the USA male and female Olympians throughout the history of the Olympics?
Distinguish between the male and female Olympians in the line graph using blue (male) and pink (female)**

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
  df = df.drop('Position', axis=1)
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
usa_gold = up[(up.NOC == 'USA') & (up.Medal == 'Gold')]
usa_gold

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size()

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size().index

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size().plot(kind='line')

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size()

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size().unstack('Gender')

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size().unstack('Gender').plot(kind='line')

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size().unstack('Gender').plot?

In [ ]:
pd.Series.plot?

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size().unstack('Gender').plot(kind='line', color=['blue', 'pink'])

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size().unstack('Gender').plot(kind='line', color=['pink', 'blue'])

**Using a bar chart, plot the 5 Olympians who have won the most gold medals from the dataset (1896 to 2008). When there is a tie, consider the number of silver medals, then bronze medals.**

In [ ]:
up.groupby(['Athlete Name','Medal']).size()

In [ ]:
(up.groupby(['Athlete Name','Medal'])
.size()
.unstack('Medal', fill_value=0)
)

In [ ]:
(up.groupby(['Athlete Name','Medal'])
.size()
.unstack('Medal', fill_value=0)
.sort_values(['Gold', 'Silver', 'Bronze'], ascending=False)
)

In [ ]:
(up.groupby(['Athlete Name','Medal'])
.size()
.unstack('Medal', fill_value=0)
.sort_values(['Gold', 'Silver', 'Bronze'], ascending=False)[['Gold', 'Silver', 'Bronze']]
)

In [ ]:
(up.groupby(['Athlete Name','Medal'])
.size()
.unstack('Medal', fill_value=0)
.sort_values(['Gold', 'Silver', 'Bronze'], ascending=False)[['Gold', 'Silver', 'Bronze']]
.head(5)
)

In [ ]:
(up.groupby(['Athlete Name','Medal'])
.size()
.unstack('Medal', fill_value=0)
.sort_values(['Gold', 'Silver', 'Bronze'], ascending=False)[['Gold', 'Silver', 'Bronze']]
.head(5)
.plot(kind='bar')
)

##Creating your own colormaps

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
  df = df.drop('Position', axis=1)
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
(up.groupby(['Athlete Name','Medal'])
.size()
.unstack('Medal', fill_value=0)
.sort_values(['Gold', 'Silver', 'Bronze'], ascending=False)[['Gold', 'Silver', 'Bronze']]
.head(5)
.plot(kind='bar')
)

In [ ]:
from matplotlib.colors import ListedColormap

In [ ]:
ListedColormap?

In [ ]:
gold_silver_bronze = ['#dbb40c','#c5c9c7','#a87900']

In [ ]:
colormap = ListedColormap(gold_silver_bronze)
colormap

In [ ]:
(up.groupby(['Athlete Name','Medal'])
.size()
.unstack('Medal', fill_value=0)
.sort_values(['Gold', 'Silver', 'Bronze'], ascending=False)[['Gold', 'Silver', 'Bronze']]
.head(5)
.plot(kind='bar', colormap=colormap)
)

##Final Challenge

For each Olympic year present in the dataset, show the US Olympian (and their sport) who has won the highest number of medals in that particular year.

- In the case of a tie, Gold > Silver > Bronze
- Include only one Olympian for each Olympic year i.e. If there are 2 Olympians in one year who have won exactly the same number and type of medals, then show only the first one based on sorting the names alphabetically by surname.

- You should show the the following columns for each Olympic year:
  - Athlete Name
  - Sport
  - Total

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
pd.set_option("display.width", 100)

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
  df = df.drop('Position', axis=1)
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

##Solution

For each Olympic year present in the dataset, show the US Olympian (and their sport) who has won the highest number of medals in that particular year.

- In the case of a tie, Gold > Silver > Bronze
- Include only one Olympian for each Olympic year i.e. If there are 2 Olympians in one year who have won exactly the same number and type of medals, then show only the first one based on sorting the names alphabetically by surname.

- You should show the the following columns for each Olympic year:
  - Athlete Name
  - Sport
  - Total

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
pd.set_option("display.width", 100)

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
  df = df.drop('Position', axis=1)
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
usa_olympian = up[up.NOC == 'USA']
usa_olympian

In [ ]:
usa_olympian.groupby(['Year', 'Athlete Name', 'Medal', 'Sport']).size()

In [ ]:
(usa_olympian.groupby(['Year', 'Athlete Name', 'Medal', 'Sport'])
.size()
.unstack('Medal', fill_value=0)
)

In [ ]:
table = (usa_olympian.groupby(['Year', 'Athlete Name', 'Sport', 'Medal'])
.size()
.unstack('Medal', fill_value=0)
)
table

In [ ]:
table = (usa_olympian.groupby(['Year', 'Athlete Name', 'Sport', 'Medal'])
.size()
.unstack('Medal', fill_value=0)
.assign(Total=table['Gold']+table['Silver']+table['Bronze'])
)
table

In [ ]:
table = (usa_olympian.groupby(['Year', 'Athlete Name', 'Sport', 'Medal'])
.size()
.unstack('Medal', fill_value=0)
.assign(Total=table['Gold']+table['Silver']+table['Bronze'])
.reset_index()
)
table

In [ ]:
for year, group in table.groupby('Year'):
  print(group)

In [ ]:
for year, group in table.groupby('Year'):
  print(group.sort_values('Total', ascending=False))

In [ ]:
for year, group in table.groupby('Year'):
  print(group.sort_values(['Total', 'Gold', 'Silver', 'Bronze', 'Athlete Name'], ascending=False))

In [ ]:
for year, group in table.groupby('Year'):
  print(group.sort_values(['Total', 'Gold', 'Silver', 'Bronze', 'Athlete Name'], ascending=False).head(1))

In [ ]:
winners = [
    group.sort_values(['Total', 'Gold', 'Silver', 'Bronze', 'Athlete Name'], ascending=False).head(1)
    for year, group in table.groupby('Year')
]
winners

In [ ]:
winners[0]

In [ ]:
type(winners[0])

In [ ]:
pd.concat(winners)

In [ ]:
pd.concat(winners)[["Year",	"Athlete Name",	"Sport", "Total"]]

In [ ]:
pd.concat(winners)[["Year",	"Athlete Name",	"Sport", "Total"]].reset_index()

In [ ]:
pd.concat(winners)[["Year",	"Athlete Name",	"Sport", "Total"]].reset_index?

In [ ]:
pd.DataFrame.reset_index?

In [ ]:
pd.concat(winners)[["Year",	"Athlete Name",	"Sport", "Total"]].reset_index(drop=True)

In [ ]:
#SDG